// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KongConfig) DeepCopyInto(out *KongConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KongConfig.
func (in *KongConfig) DeepCopy() *KongConfig {
	if in == nil {
		return nil
	}
	out := new(KongConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KongConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KongConfigList) DeepCopyInto(out *KongConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KongConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KongConfigList.
func (in *KongConfigList) DeepCopy() *KongConfigList {
	if in == nil {
		return nil
	}
	out := new(KongConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KongConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KongConfigSpec) DeepCopyInto(out *KongConfigSpec) {
	*out = *in
	in.Service.DeepCopyInto(&out.Service)
	in.Route.DeepCopyInto(&out.Route)
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KongConfigSpec.
func (in *KongConfigSpec) DeepCopy() *KongConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KongConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KongConfigStatus) DeepCopyInto(out *KongConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KongConfigStatus.
func (in *KongConfigStatus) DeepCopy() *KongConfigStatus {
	if in == nil {
		return nil
	}
	out := new(KongConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KongPluginCORS) DeepCopyInto(out *KongPluginCORS) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExposedHeaders != nil {
		in, out := &in.ExposedHeaders, &out.ExposedHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxAge != nil {
		in, out := &in.MaxAge, &out.MaxAge
		*out = new(int32)
		**out = **in
	}
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(bool)
		**out = **in
	}
	if in.PreflightContinue != nil {
		in, out := &in.PreflightContinue, &out.PreflightContinue
		*out = new(bool)
		**out = **in
	}
	if in.Origins != nil {
		in, out := &in.Origins, &out.Origins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KongPluginCORS.
func (in *KongPluginCORS) DeepCopy() *KongPluginCORS {
	if in == nil {
		return nil
	}
	out := new(KongPluginCORS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KongPluginIpRestriction) DeepCopyInto(out *KongPluginIpRestriction) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Deny != nil {
		in, out := &in.Deny, &out.Deny
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KongPluginIpRestriction.
func (in *KongPluginIpRestriction) DeepCopy() *KongPluginIpRestriction {
	if in == nil {
		return nil
	}
	out := new(KongPluginIpRestriction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KongPluginJwt) DeepCopyInto(out *KongPluginJwt) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.SecretIsBase64 != nil {
		in, out := &in.SecretIsBase64, &out.SecretIsBase64
		*out = new(bool)
		**out = **in
	}
	if in.RunOnPreflight != nil {
		in, out := &in.RunOnPreflight, &out.RunOnPreflight
		*out = new(bool)
		**out = **in
	}
	if in.UriParamNames != nil {
		in, out := &in.UriParamNames, &out.UriParamNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HeaderNames != nil {
		in, out := &in.HeaderNames, &out.HeaderNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaximumExpiration != nil {
		in, out := &in.MaximumExpiration, &out.MaximumExpiration
		*out = new(int32)
		**out = **in
	}
	if in.CookieNames != nil {
		in, out := &in.CookieNames, &out.CookieNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KongPluginJwt.
func (in *KongPluginJwt) DeepCopy() *KongPluginJwt {
	if in == nil {
		return nil
	}
	out := new(KongPluginJwt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KongPluginKeyAuth) DeepCopyInto(out *KongPluginKeyAuth) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.KeyNames != nil {
		in, out := &in.KeyNames, &out.KeyNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RunOnPreflight != nil {
		in, out := &in.RunOnPreflight, &out.RunOnPreflight
		*out = new(bool)
		**out = **in
	}
	if in.HideCredentials != nil {
		in, out := &in.HideCredentials, &out.HideCredentials
		*out = new(bool)
		**out = **in
	}
	if in.KeyInBody != nil {
		in, out := &in.KeyInBody, &out.KeyInBody
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KongPluginKeyAuth.
func (in *KongPluginKeyAuth) DeepCopy() *KongPluginKeyAuth {
	if in == nil {
		return nil
	}
	out := new(KongPluginKeyAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KongPluginRateLimiting) DeepCopyInto(out *KongPluginRateLimiting) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.HideClientHeaders != nil {
		in, out := &in.HideClientHeaders, &out.HideClientHeaders
		*out = new(bool)
		**out = **in
	}
	if in.FaultTolerant != nil {
		in, out := &in.FaultTolerant, &out.FaultTolerant
		*out = new(bool)
		**out = **in
	}
	if in.RedisPort != nil {
		in, out := &in.RedisPort, &out.RedisPort
		*out = new(int32)
		**out = **in
	}
	if in.RedisDatabase != nil {
		in, out := &in.RedisDatabase, &out.RedisDatabase
		*out = new(int32)
		**out = **in
	}
	if in.RedisTimeout != nil {
		in, out := &in.RedisTimeout, &out.RedisTimeout
		*out = new(int32)
		**out = **in
	}
	if in.Year != nil {
		in, out := &in.Year, &out.Year
		*out = new(int32)
		**out = **in
	}
	if in.Month != nil {
		in, out := &in.Month, &out.Month
		*out = new(int32)
		**out = **in
	}
	if in.Day != nil {
		in, out := &in.Day, &out.Day
		*out = new(int32)
		**out = **in
	}
	if in.Hour != nil {
		in, out := &in.Hour, &out.Hour
		*out = new(int32)
		**out = **in
	}
	if in.Minute != nil {
		in, out := &in.Minute, &out.Minute
		*out = new(int32)
		**out = **in
	}
	if in.Second != nil {
		in, out := &in.Second, &out.Second
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KongPluginRateLimiting.
func (in *KongPluginRateLimiting) DeepCopy() *KongPluginRateLimiting {
	if in == nil {
		return nil
	}
	out := new(KongPluginRateLimiting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KongPluginRequestTermination) DeepCopyInto(out *KongPluginRequestTermination) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.StatusCode != nil {
		in, out := &in.StatusCode, &out.StatusCode
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KongPluginRequestTermination.
func (in *KongPluginRequestTermination) DeepCopy() *KongPluginRequestTermination {
	if in == nil {
		return nil
	}
	out := new(KongPluginRequestTermination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KongPlugins) DeepCopyInto(out *KongPlugins) {
	*out = *in
	in.Cors.DeepCopyInto(&out.Cors)
	in.IpRestriction.DeepCopyInto(&out.IpRestriction)
	in.Jwt.DeepCopyInto(&out.Jwt)
	in.RequestTermination.DeepCopyInto(&out.RequestTermination)
	in.KeyAuth.DeepCopyInto(&out.KeyAuth)
	in.RateLimiting.DeepCopyInto(&out.RateLimiting)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KongPlugins.
func (in *KongPlugins) DeepCopy() *KongPlugins {
	if in == nil {
		return nil
	}
	out := new(KongPlugins)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KongRouteConfig) DeepCopyInto(out *KongRouteConfig) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HttpsRedirectStatusCode != nil {
		in, out := &in.HttpsRedirectStatusCode, &out.HttpsRedirectStatusCode
		*out = new(int32)
		**out = **in
	}
	if in.RegexPriority != nil {
		in, out := &in.RegexPriority, &out.RegexPriority
		*out = new(int32)
		**out = **in
	}
	if in.StripPath != nil {
		in, out := &in.StripPath, &out.StripPath
		*out = new(bool)
		**out = **in
	}
	if in.PreserveHost != nil {
		in, out := &in.PreserveHost, &out.PreserveHost
		*out = new(bool)
		**out = **in
	}
	if in.Protocols != nil {
		in, out := &in.Protocols, &out.Protocols
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Plugins.DeepCopyInto(&out.Plugins)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KongRouteConfig.
func (in *KongRouteConfig) DeepCopy() *KongRouteConfig {
	if in == nil {
		return nil
	}
	out := new(KongRouteConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KongServiceConfig) DeepCopyInto(out *KongServiceConfig) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.Retries != nil {
		in, out := &in.Retries, &out.Retries
		*out = new(int32)
		**out = **in
	}
	if in.ConnectTimeout != nil {
		in, out := &in.ConnectTimeout, &out.ConnectTimeout
		*out = new(int32)
		**out = **in
	}
	if in.WriteTimeout != nil {
		in, out := &in.WriteTimeout, &out.WriteTimeout
		*out = new(int32)
		**out = **in
	}
	if in.ReadTimeout != nil {
		in, out := &in.ReadTimeout, &out.ReadTimeout
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KongServiceConfig.
func (in *KongServiceConfig) DeepCopy() *KongServiceConfig {
	if in == nil {
		return nil
	}
	out := new(KongServiceConfig)
	in.DeepCopyInto(out)
	return out
}
