# permissions for end users to edit kongconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kongconfig-editor-role
rules:
- apiGroups:
  - kong.pyfdtic.com
  resources:
  - kongconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kong.pyfdtic.com
  resources:
  - kongconfigs/status
  verbs:
  - get
