# permissions for end users to view kongconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kongconfig-viewer-role
rules:
- apiGroups:
  - kong.pyfdtic.com
  resources:
  - kongconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kong.pyfdtic.com
  resources:
  - kongconfigs/status
  verbs:
  - get
